# Copyright 2024 Bytedance Ltd. and/or its affiliates  # 注释：版权声明
#  # 注释：空行占位
# Licensed under the Apache License, Version 2.0 (the "License");  # 注释：Apache 2.0 许可证声明
# you may not use this file except in compliance with the License.  # 注释：使用需遵守许可证
# You may obtain a copy of the License at  # 注释：许可证获取提示
#  # 注释：空行占位
#     http://www.apache.org/licenses/LICENSE-2.0  # 注释：许可证链接
#  # 注释：空行占位
# Unless required by applicable law or agreed to in writing, software  # 注释：免责声明开头
# distributed under the License is distributed on an "AS IS" BASIS,  # 注释：按现状提供
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  # 注释：无担保声明
# See the License for the specific language governing permissions and  # 注释：更多许可条款
# limitations under the License.  # 注释：许可限制说明

"""
模块用途：解析模型输出中的工具调用（tool calls），支持 Hermes 与 GPT-OSS 格式。  # 注释：模块用途
输入：模型生成的 token id 列表。  # 注释：输入说明
输出：纯文本内容与 FunctionCall 列表。  # 注释：输出说明
关键依赖：regex、pydantic、verl.utils.ray_utils、rollout_trace。  # 注释：依赖说明
典型用法：  # 注释：用法标题
- parser = ToolParser.get_tool_parser("hermes", tokenizer); await parser.extract_tool_calls(ids)  # 注释：示例
调用路径概览：  # 注释：调用路径标题
- ToolAgentLoop.run -> ToolParser.extract_tool_calls。  # 注释：调用链
"""  # 注释：模块 docstring 结束

import json  # 注释：标准库，JSON 解析
import logging  # 注释：标准库，日志
import os  # 注释：标准库，环境变量
from abc import ABC, abstractmethod  # 注释：抽象基类

import regex  # 注释：第三方库，正则匹配（支持更强语法）
from pydantic import BaseModel  # 注释：第三方库，数据模型

from verl.utils.ray_utils import get_event_loop  # 注释：项目内工具，获取事件循环
from verl.utils.rollout_trace import rollout_trace_op  # 注释：项目内装饰器，记录 rollout trace

logger = logging.getLogger(__file__)  # 注释：获取模块 logger
logger.setLevel(os.getenv("VERL_LOGGING_LEVEL", "WARN"))  # 注释：设置日志级别


class FunctionCall(BaseModel):  # 注释：工具调用结构体
    """
    功能：描述一次工具调用的名称与参数（JSON 字符串）。  # 注释：类用途
    参数：通过字段 name/arguments 提供。  # 注释：参数说明
    返回：实例化后的 FunctionCall。  # 注释：返回值说明
    副作用：无。  # 注释：副作用说明
    异常/边界条件：arguments 可能不是合法 JSON（需要上层校验）。  # 注释：异常说明
    最小示例：  # 注释：最小示例标题
    - FunctionCall(name="calc", arguments='{"x":1}')  # 注释：示例
    调用路径依赖：  # 注释：调用路径说明标题
    - 所在位置：verl/experimental/agent_loop/tool_parser.py::FunctionCall。  # 注释：类位置
    - 典型调用路径：ToolParser.extract_tool_calls -> FunctionCall(...)。  # 注释：调用链
    - 被谁调用：HermesToolParser/GptOssToolParser。  # 注释：调用方说明
    - 调用了谁（项目内）：无。  # 注释：项目内依赖
    - 调用了谁（关键外部依赖）：pydantic.BaseModel。  # 注释：外部依赖
    """  # 注释：类 docstring 结束
    arguments: str  # 注释：工具调用参数（JSON 字符串）
    """
    The arguments to call the function with, as generated by the model in JSON
    format. Note that the model does not always generate valid JSON, and may
    hallucinate parameters not defined by your function schema. Validate the
    arguments in your code before calling your function.
    """  # 注释：保留英文说明（参数语义）

    name: str  # 注释：工具名称
    """The name of the function to call."""  # 注释：保留英文说明


class ToolParser(ABC):  # 注释：工具解析器基类
    """
    功能：定义工具解析器的统一接口与注册机制。  # 注释：类用途
    参数：tokenizer 由子类初始化传入。  # 注释：参数说明
    返回：子类实例提供 extract_tool_calls。  # 注释：返回值说明
    副作用：类级注册表更新。  # 注释：副作用说明
    异常/边界条件：未知 parser 名称会抛 ValueError。  # 注释：异常说明
    最小示例：  # 注释：最小示例标题
    - ToolParser.get_tool_parser("hermes", tokenizer)。  # 注释：示例
    调用路径依赖：  # 注释：调用路径说明标题
    - 所在位置：verl/experimental/agent_loop/tool_parser.py::ToolParser。  # 注释：类位置
    - 典型调用路径：ToolAgentLoop._get_tool_parser -> ToolParser.get_tool_parser。  # 注释：调用链
    - 被谁调用：verl/experimental/agent_loop/tool_agent_loop.py。  # 注释：调用方说明
    - 调用了谁（项目内）：get_event_loop、rollout_trace_op。  # 注释：项目内依赖
    - 调用了谁（关键外部依赖）：regex、pydantic。  # 注释：外部依赖
    """  # 注释：类 docstring 结束
    _registry: dict[str, type["ToolParser"]] = {}  # 注释：工具解析器注册表

    def __init__(self, tokenizer) -> None:  # 注释：初始化基类
        """
        功能：保存 tokenizer 供子类解码使用。  # 注释：函数用途
        参数：  # 注释：参数说明标题
        - tokenizer：用于 decode 的 tokenizer。  # 注释：参数含义
        返回：  # 注释：返回值说明标题
        - None。  # 注释：返回值语义
        副作用：设置 self.tokenizer。  # 注释：副作用说明
        异常/边界条件：无。  # 注释：异常说明
        最小示例：  # 注释：最小示例标题
        - ToolParser(tokenizer)。  # 注释：示例
        调用路径依赖：  # 注释：调用路径说明标题
        - 所在位置：verl/experimental/agent_loop/tool_parser.py::ToolParser.__init__。  # 注释：函数位置
        - 典型调用路径：HermesToolParser.__init__ -> super().__init__。  # 注释：调用链
        - 被谁调用：各子类 __init__。  # 注释：调用方说明
        - 调用了谁（项目内）：无。  # 注释：项目内依赖
        - 调用了谁（关键外部依赖）：无。  # 注释：外部依赖
        """  # 注释：函数 docstring 结束
        self.tokenizer = tokenizer  # 注释：保存 tokenizer

    @abstractmethod  # 注释：抽象方法装饰器
    async def extract_tool_calls(self, responses_ids: list[int]) -> tuple[str, list[FunctionCall]]:  # 注释：抽象接口
        """
        Extract tool calls from the responses.

        Args:
            responses_ids (List[int]): The ids of the responses.

        Returns:
            Tuple[str, List[FunctionCall]]: Content and extracted tool calls.
        """  # 注释：保留英文说明
        raise NotImplementedError  # 注释：抽象方法占位

    @classmethod  # 注释：类方法
    def get_tool_parser(cls, name: str, tokenizer):  # 注释：根据名称获取解析器
        """
        功能：从注册表中实例化指定名称的 ToolParser。  # 注释：函数用途
        参数：  # 注释：参数说明标题
        - name (str)：解析器名称。  # 注释：参数含义
        - tokenizer：用于解析的 tokenizer。  # 注释：参数含义
        返回：  # 注释：返回值说明标题
        - ToolParser 子类实例。  # 注释：返回值语义
        副作用：无。  # 注释：副作用说明
        异常/边界条件：未注册名称抛 ValueError。  # 注释：异常说明
        最小示例：  # 注释：最小示例标题
        - ToolParser.get_tool_parser("hermes", tokenizer)。  # 注释：示例
        调用路径依赖：  # 注释：调用路径说明标题
        - 所在位置：verl/experimental/agent_loop/tool_parser.py::ToolParser.get_tool_parser。  # 注释：函数位置
        - 典型调用路径：ToolAgentLoop._get_tool_parser -> get_tool_parser。  # 注释：调用链
        - 被谁调用：verl/experimental/agent_loop/tool_agent_loop.py。  # 注释：调用方说明
        - 调用了谁（项目内）：注册表 _registry。  # 注释：项目内依赖
        - 调用了谁（关键外部依赖）：无。  # 注释：外部依赖
        """  # 注释：函数 docstring 结束
        if name not in cls._registry:  # 注释：名称未注册
            raise ValueError(f"Unknown tool parser: {name}")  # 注释：抛出异常
        return cls._registry[name](tokenizer)  # 注释：实例化并返回

    @classmethod  # 注释：类方法
    def register(cls, name: str):  # 注释：注册装饰器
        """
        功能：将子类注册到解析器名称。  # 注释：函数用途
        参数：  # 注释：参数说明标题
        - name (str)：解析器名称。  # 注释：参数含义
        返回：  # 注释：返回值说明标题
        - decorator：装饰器函数。  # 注释：返回值语义
        副作用：更新类级注册表。  # 注释：副作用说明
        异常/边界条件：无。  # 注释：异常说明
        最小示例：  # 注释：最小示例标题
        - @ToolParser.register("hermes") class HermesToolParser(...): ...  # 注释：示例
        调用路径依赖：  # 注释：调用路径说明标题
        - 所在位置：verl/experimental/agent_loop/tool_parser.py::ToolParser.register。  # 注释：函数位置
        - 典型调用路径：模块导入 -> 装饰器执行 -> 更新注册表。  # 注释：调用链
        - 被谁调用：HermesToolParser/GptOssToolParser 类定义时。  # 注释：调用方说明
        - 调用了谁（项目内）：_registry。  # 注释：项目内依赖
        - 调用了谁（关键外部依赖）：无。  # 注释：外部依赖
        """  # 注释：函数 docstring 结束
        def decorator(subclass: type[ToolParser]) -> type[ToolParser]:  # 注释：装饰器函数
            cls._registry[name] = subclass  # 注释：注册子类
            return subclass  # 注释：返回子类

        return decorator  # 注释：返回装饰器


@ToolParser.register("hermes")  # 注释：注册 hermes 解析器
class HermesToolParser(ToolParser):  # 注释：Hermes 格式工具解析器
    """
    功能：解析 Hermes 格式的 <tool_call>... JSON ...</tool_call>。  # 注释：类用途
    参数：tokenizer。  # 注释：参数说明
    返回：HermesToolParser 实例。  # 注释：返回值说明
    副作用：编译正则表达式。  # 注释：副作用说明
    异常/边界条件：JSON 解析失败将记录日志。  # 注释：异常说明
    最小示例：  # 注释：最小示例标题
    - parser = HermesToolParser(tokenizer); await parser.extract_tool_calls(ids)。  # 注释：示例
    调用路径依赖：  # 注释：调用路径说明标题
    - 所在位置：verl/experimental/agent_loop/tool_parser.py::HermesToolParser。  # 注释：类位置
    - 典型调用路径：ToolAgentLoop -> ToolParser.get_tool_parser -> HermesToolParser。  # 注释：调用链
    - 被谁调用：tool_agent_loop.py。  # 注释：调用方说明
    - 调用了谁（项目内）：get_event_loop、rollout_trace_op。  # 注释：项目内依赖
    - 调用了谁（关键外部依赖）：regex、json。  # 注释：外部依赖
    """  # 注释：类 docstring 结束
    """Adapted from https://github.com/vllm-project/vllm/blob/v0.9.1/vllm/entrypoints/openai/tool_parsers/hermes_tool_parser.py"""  # 注释：保留英文来源

    def __init__(self, tokenizer) -> None:  # 注释：初始化 Hermes 解析器
        """
        功能：初始化 tokenizer 与 Hermes 工具调用正则。  # 注释：函数用途
        参数：tokenizer。  # 注释：参数含义
        返回：None。  # 注释：返回值语义
        副作用：设置工具调用起止标记与正则。  # 注释：副作用说明
        异常/边界条件：无。  # 注释：异常说明
        最小示例：  # 注释：最小示例标题
        - HermesToolParser(tokenizer)。  # 注释：示例
        调用路径依赖：  # 注释：调用路径说明标题
        - 所在位置：verl/experimental/agent_loop/tool_parser.py::HermesToolParser.__init__。  # 注释：函数位置
        - 典型调用路径：ToolParser.get_tool_parser -> HermesToolParser(...)。  # 注释：调用链
        - 被谁调用：ToolParser.get_tool_parser。  # 注释：调用方说明
        - 调用了谁（项目内）：ToolParser.__init__。  # 注释：项目内依赖
        - 调用了谁（关键外部依赖）：regex.compile。  # 注释：外部依赖
        """  # 注释：函数 docstring 结束
        super().__init__(tokenizer)  # 注释：调用父类初始化

        self.tool_call_start_token: str = "<tool_call>"  # 注释：工具调用起始标记
        self.tool_call_end_token: str = "</tool_call>"  # 注释：工具调用结束标记
        self.tool_call_regex = regex.compile(r"<tool_call>(.*?)</tool_call>", regex.DOTALL)  # 注释：工具调用正则

    @rollout_trace_op  # 注释：记录 rollout trace
    async def extract_tool_calls(self, responses_ids: list[int]) -> tuple[str, list[FunctionCall]]:  # 注释：解析工具调用
        """
        功能：将 token id 解码为文本，并提取 Hermes 工具调用 JSON。  # 注释：函数用途
        参数：responses_ids (list[int])：模型输出 token id。  # 注释：参数含义
        返回：tuple[str, list[FunctionCall]]：正文与工具调用列表。  # 注释：返回值语义
        副作用：可能记录日志；不会修改输入。  # 注释：副作用说明
        异常/边界条件：JSON 解析失败记录错误日志并跳过。  # 注释：异常说明
        最小示例：  # 注释：最小示例标题
        - await parser.extract_tool_calls(ids) -> (content, [FunctionCall(...)])。  # 注释：示例
        调用路径依赖：  # 注释：调用路径说明标题
        - 所在位置：verl/experimental/agent_loop/tool_parser.py::HermesToolParser.extract_tool_calls。  # 注释：函数位置
        - 典型调用路径：ToolAgentLoop.run -> ToolParser.extract_tool_calls。  # 注释：调用链
        - 被谁调用：tool_agent_loop.py。  # 注释：调用方说明
        - 调用了谁（项目内）：get_event_loop。  # 注释：项目内依赖
        - 调用了谁（关键外部依赖）：json.loads、regex。  # 注释：外部依赖
        """  # 注释：函数 docstring 结束
        loop = get_event_loop()  # 注释：获取事件循环
        text = await loop.run_in_executor(None, self.tokenizer.decode, responses_ids)  # 注释：在线程池中解码
        if self.tool_call_start_token not in text or self.tool_call_end_token not in text:  # 注释：无工具标记
            return text, []  # 注释：返回原文本与空列表

        matches = self.tool_call_regex.findall(text)  # 注释：匹配工具调用片段
        function_calls = []  # 注释：初始化 FunctionCall 列表
        for match in matches:  # 注释：遍历匹配片段
            try:  # 注释：捕获 JSON 解析异常
                function_call = json.loads(match)  # 注释：解析 JSON
                name, arguments = function_call["name"], function_call["arguments"]  # 注释：提取字段
                function_calls.append(FunctionCall(name=name, arguments=json.dumps(arguments, ensure_ascii=False)))  # 注释：构造 FunctionCall
            except Exception as e:  # 注释：解析失败
                logger.error(f"Failed to decode tool call: {e}")  # 注释：记录错误

        # remaing text exclude tool call tokens  # 注释：原注释保留（移除工具标记）
        content = self.tool_call_regex.sub("", text)  # 注释：去掉工具调用片段

        return content, function_calls  # 注释：返回正文与工具调用


@ToolParser.register("gpt-oss")  # 注释：注册 gpt-oss 解析器
class GptOssToolParser(ToolParser):  # 注释：GPT-OSS 工具解析器
    """
    Tool parser for gpt-oss model.
    Adapted from https://github.com/sgl-project/sglang/blob/main/python/sglang/srt/function_call/gpt_oss_detector.py

    Args:
        tokenizer: The tokenizer to use.
    """  # 注释：保留英文说明

    def __init__(self, tokenizer) -> None:  # 注释：初始化 GPT-OSS 解析器
        """
        功能：初始化 GPT-OSS 的 COT/工具调用正则表达式。  # 注释：函数用途
        参数：tokenizer。  # 注释：参数含义
        返回：None。  # 注释：返回值语义
        副作用：编译正则并设置成员变量。  # 注释：副作用说明
        异常/边界条件：无。  # 注释：异常说明
        最小示例：  # 注释：最小示例标题
        - GptOssToolParser(tokenizer)。  # 注释：示例
        调用路径依赖：  # 注释：调用路径说明标题
        - 所在位置：verl/experimental/agent_loop/tool_parser.py::GptOssToolParser.__init__。  # 注释：函数位置
        - 典型调用路径：ToolParser.get_tool_parser -> GptOssToolParser(...)。  # 注释：调用链
        - 被谁调用：ToolParser.get_tool_parser。  # 注释：调用方说明
        - 调用了谁（项目内）：ToolParser.__init__。  # 注释：项目内依赖
        - 调用了谁（关键外部依赖）：regex.compile。  # 注释：外部依赖
        """  # 注释：函数 docstring 结束
        super().__init__(tokenizer)  # 注释：调用父类初始化
        # check https://cookbook.openai.com/articles/openai-harmony for more details.  # 注释：原注释保留（参考文档）
        self.cot_pattern = regex.compile(  # 注释：COT 匹配正则
            r"<\|start\|>assistant<\|channel\|>analysis<\|message\|>.*?<\|end\|>", regex.DOTALL  # 注释：正则表达式
        )  # 注释：正则结束
        # <|start|>assistant may be pre-appended in prompts, so we need to remove it.  # 注释：原注释保留
        self.partial_cot_pattern = regex.compile(r"<\|channel\|>analysis<\|message\|>(.*?)<\|end\|>", regex.DOTALL)  # 注释：部分 COT 正则
        self.tool_call_pattern = regex.compile(  # 注释：工具调用正则
            r"<\|start\|>assistant<\|channel\|>[^<]* to=functions\.([^<]+) "  # 注释：正则片段
            r"<\|constrain\|>json<\|message\|>(.*?)<\|call\|>",  # 注释：正则片段
            regex.DOTALL,  # 注释：DOTALL 模式
        )  # 注释：正则结束

    @rollout_trace_op  # 注释：记录 rollout trace
    async def extract_tool_calls(self, responses_ids: list[int]) -> tuple[str, list[FunctionCall]]:  # 注释：解析 GPT-OSS 工具调用
        """
        功能：解码 token 并解析 GPT-OSS 格式的函数调用。  # 注释：函数用途
        参数：responses_ids (list[int])：模型输出 token id。  # 注释：参数含义
        返回：tuple[str, list[FunctionCall]]：正文与工具调用列表。  # 注释：返回值语义
        副作用：可能记录日志；不会修改输入。  # 注释：副作用说明
        异常/边界条件：解析失败时记录日志并跳过。  # 注释：异常说明
        最小示例：  # 注释：最小示例标题
        - await parser.extract_tool_calls(ids) -> (content, [FunctionCall(...)]).  # 注释：示例
        调用路径依赖：  # 注释：调用路径说明标题
        - 所在位置：verl/experimental/agent_loop/tool_parser.py::GptOssToolParser.extract_tool_calls。  # 注释：函数位置
        - 典型调用路径：ToolAgentLoop.run -> ToolParser.extract_tool_calls。  # 注释：调用链
        - 被谁调用：tool_agent_loop.py。  # 注释：调用方说明
        - 调用了谁（项目内）：get_event_loop。  # 注释：项目内依赖
        - 调用了谁（关键外部依赖）：regex。  # 注释：外部依赖
        """  # 注释：函数 docstring 结束
        loop = get_event_loop()  # 注释：获取事件循环
        # We need to keep special tokens for gpt-oss model for better tool call extraction.  # 注释：原注释保留
        text = await loop.run_in_executor(None, lambda: self.tokenizer.decode(responses_ids, skip_special_tokens=False))  # 注释：解码文本（保留特殊 token）
        # Need to remove padding tokens for better tool call extraction.  # 注释：原注释保留
        text = text.replace(self.tokenizer.pad_token, "")  # 注释：去掉 padding token
        # Need to reomve COT since COT may contain tool call tokens.But they are not valid tool calls.  # 注释：原注释保留
        text = regex.sub(self.cot_pattern, "", text)  # 注释：移除完整 COT 段
        text = regex.sub(self.partial_cot_pattern, "", text)  # 注释：移除部分 COT 段

        # check if there are tool calls in the text by re.findall  # 注释：原注释保留
        matches = regex.findall(self.tool_call_pattern, text)  # 注释：查找工具调用
        if not matches:  # 注释：无工具调用
            return text, []  # 注释：返回原文本与空列表

        function_calls = []  # 注释：初始化 FunctionCall 列表
        for match in matches:  # 注释：遍历匹配项
            try:  # 注释：捕获解析异常
                name, arguments = match[0], match[1]  # 注释：提取名称与参数
                # don't check if arguments is valid JSON and leave it to client  # 注释：原注释保留
                function_calls.append(FunctionCall(name=name, arguments=arguments))  # 注释：构造 FunctionCall
            except Exception as e:  # 注释：解析失败
                logger.error(f"Failed to decode tool call: {e}")  # 注释：记录错误

        # remaing text exclude tool call tokens  # 注释：原注释保留
        content = regex.sub(self.tool_call_pattern, "", text)  # 注释：移除工具调用片段

        return content, function_calls  # 注释：返回正文与工具调用
